name: Kern Valley Apps
shortName: KRV Apps
version: 1.0.0-2021-12-29
lang: en
dir: ltr
display: standalone
orientation: any
description: "A directory of KernValley.US Web Apps"
icons-file: /img/icons.svg
theme:
  color: '#007bff'
  background: '#242424'
icons:
  - src: /img/favicon.svg
    type: image/svg+xml
    sizes: 150x150
    purpose: maskable any
  - src: /img/apple-touch-icon.png
    rel: apple-touch-icon
    type: image/png
    sizes: 180x180
  - src: /img/icon-512.png
    type: image/png
    sizes: 512x512
    purpose: maskable any
  - src: /img/icon-192.png
    type: image/png
    sizes: 192x192
    purpose: maskable any
  - src: /img/icon-32.png
    type: image/png
    sizes: 32x32
  - src: /img/icon-16.png
    type: image/png
    sizes: 16x16
screenshots:
  - src: https://i.imgur.com/w8p9UNf.png
    sizes: 1354x662
  - src: https://i.imgur.com/w8p9UNfh.png
    sizes: 1024x501
    type: image/png
  - src: https://i.imgur.com/w8p9UNfl.png
    sizes: 640x313
    type: image/png
  - src: https://i.imgur.com/w8p9UNfm.png
    sizes: 320x156
    type: image/png
  - src: https://i.imgur.com/w8p9UNft.png
    sizes: 160x78
    type: image/png
# https://web.dev/app-shortcuts/
related_applications:
  - platform: webapp
    url: https://apps.kernvalley.us/manifest.json
features:
  - Quick access to all KernValley.US web apps
  - Offline browsing supported
  - Dark mode support
  - Integtation with system sharing
# https://github.com/w3c/manifest/wiki/Categories
categories:
  - productivity
  - utilities
